default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
minimum_pre_commit_version: "1.4.3"

repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.4.5
    hooks:
      - id: conventional-gitmoji
