name: Check and bump

on:
  push:
    branches:
      - "**"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'main' &&
      github.ref_type == 'branch' &&
      !startsWith(github.event.head_commit.message, '🔖 bump(release):') &&
      !startsWith(github.event.head_commit.message, 'bump(release):')
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Checkout
        if: github.actor == 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}
          submodules: recursive

      - name: Checkout
        if: github.actor != 'dependabot[bot]'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: recursive

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          extra_requirements: "cz-conventional-gitmoji"
